/**
 * Polished single-job brief — opened from Priority Outreach permit links.
 * Data: data/exports/job_briefs.json (generated by the pipeline).
 */

function escapeHtml(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function money(value) {
  if (value == null || value === "") return "—";
  const n = Number(value);
  if (Number.isNaN(n)) return "—";
  return `$${Math.round(n).toLocaleString("en-US")}`;
}

function pct(value) {
  if (value == null || value === "") return "—";
  const n = Number(value);
  if (Number.isNaN(n)) return "—";
  return `${Math.round(n)}%`;
}

function dash(value) {
  const s = value == null ? "" : String(value).trim();
  return s ? escapeHtml(s) : "—";
}

function row(label, valueHtml) {
  return `<tr><th>${escapeHtml(label)}</th><td>${valueHtml}</td></tr>`;
}

function renderJob(job, generatedAt) {
  document.title = `CorridorIQ — ${job.permit_number || "Job"} brief`;
  document.getElementById("pageTitle").textContent = `Permit ${job.permit_number || ""}`;
  document.getElementById("jobHeading").textContent = job.permit_number || "Permit";
  document.getElementById("jobBadge").textContent = job.project_category || "Job brief";
  document.getElementById("jobSubmeta").textContent = [
    job.jurisdiction_name || job.city,
    job.issued_date && `Issued ${job.issued_date}`,
    job.opportunity_score != null && `Score ${Math.round(Number(job.opportunity_score))}`,
  ]
    .filter(Boolean)
    .join(" · ");
  document.getElementById("generatedAt").textContent = generatedAt
    ? `Data as of ${generatedAt}`
    : "";

  const leadNote = job.has_named_party
    ? "Named party from the public feed."
    : job.outreach_lead && String(job.outreach_lead).startsWith("Project ·")
      ? "City published a project/subdivision label only — contractor contacts are not on this open layer."
      : "No contractor / applicant name in the public source for this permit.";

  const materials = Array.isArray(job.materials) ? job.materials : [];
  const materialRows = materials.length
    ? materials
        .map(
          (m) =>
            `<tr><td>${dash(m.material_name)}</td><td class="report-score-cell">${pct(
              m.confidence_pct
            )}</td><td>${dash(m.rationale)}</td></tr>`
        )
        .join("")
    : `<tr><td colspan="3">No material lines estimated for this job yet.</td></tr>`;

  const addressBits = [job.job_address, job.city, job.state, job.zip]
    .filter((x) => x && String(x).trim())
    .join(", ");

  document.getElementById("jobBody").innerHTML = `
    <h1 class="report-doc-title">Polished job brief</h1>
    <aside class="report-callout">
      Live public-permit data only. Outreach lead: <strong>${escapeHtml(
        job.outreach_lead || "Not in source"
      )}</strong>. ${escapeHtml(leadNote)}
    </aside>

    <h2 class="report-section-title">At a glance</h2>
    <div class="report-table-wrap">
      <table class="report-table job-facts-table">
        <tbody>
          ${row("Permit", `<strong>${dash(job.permit_number)}</strong>`)}
          ${row("Market", dash(job.jurisdiction_name || job.city))}
          ${row("Address", dash(addressBits || job.job_address))}
          ${row("Opportunity score", `<span class="report-score-cell">${
            job.opportunity_score != null ? Math.round(Number(job.opportunity_score)) : "—"
          }</span>`)}
          ${row("Confidence", pct(job.confidence_score))}
          ${row("Category", dash(job.project_category))}
          ${row("Construction stage", dash(job.construction_stage))}
          ${row("Est. material value", money(job.estimated_material_value))}
          ${row("Est. gross profit", money(job.estimated_gross_profit))}
          ${row("Permit valuation", money(job.valuation))}
          ${row("Square footage", job.square_footage != null ? escapeHtml(String(job.square_footage)) : "—")}
        </tbody>
      </table>
    </div>

    <h2 class="report-section-title">Who to call</h2>
    <div class="report-table-wrap">
      <table class="report-table job-facts-table">
        <tbody>
          ${row("Outreach lead", `<strong>${dash(job.outreach_lead)}</strong>`)}
          ${row("General contractor", dash(job.general_contractor_name))}
          ${row("Plumbing contractor", dash(job.plumbing_contractor_name))}
          ${row("Owner", dash(job.owner_name))}
          ${row("License #", dash(job.contractor_license_number))}
          ${row("Project / subdivision", dash(job.project_description))}
        </tbody>
      </table>
    </div>
    <p>${escapeHtml(leadNote)} For Project · or blank leads, look up this permit in the city portal with the permit number and address.</p>

    <h2 class="report-section-title">Job details</h2>
    <div class="report-table-wrap">
      <table class="report-table job-facts-table">
        <tbody>
          ${row("Status", dash(job.status))}
          ${row("Permit type", dash(job.permit_type))}
          ${row("Subtype", dash(job.permit_subtype))}
          ${row("Filed", dash(job.filed_date))}
          ${row("Issued", dash(job.issued_date))}
          ${row("Expires", dash(job.expiration_date))}
          ${row("Finaled", dash(job.finaled_date))}
          ${row("Parcel", dash(job.parcel_number))}
          ${row("Likely plumbing scope", dash(job.estimated_plumbing_scope))}
          ${row("Description", dash(job.description))}
        </tbody>
      </table>
    </div>

    <h2 class="report-section-title">Likely materials</h2>
    <div class="report-table-wrap">
      <table class="report-table">
        <thead><tr><th>Material</th><th>Confidence</th><th>Rationale</th></tr></thead>
        <tbody>${materialRows}</tbody>
      </table>
    </div>

    <h2 class="report-section-title">Recommended next actions</h2>
    <ol class="report-actions">
      <li>Confirm the outreach lead (or look up the filer in the city portal if Project · / blank).</li>
      <li>Open with availability on: ${escapeHtml(
        job.estimated_plumbing_scope || "the likely plumbing scope above"
      )}.</li>
      <li>Ask who buys materials for this job (PM vs purchasing) and offer will-call / delivery.</li>
      <li>Attach a short quote skeleton using the material list before the first call.</li>
    </ol>

    <p class="report-doc-submeta" style="margin-top:24px;">
      Jurisdiction key: <code>${escapeHtml(job.jurisdiction)}</code>
      · Score floor data only — nothing invented.
    </p>
  `;

  document.getElementById("jobBrief").style.display = "block";
}

async function init() {
  const loading = document.getElementById("loadingState");
  const error = document.getElementById("errorState");
  document.getElementById("printJobBtn")?.addEventListener("click", () => window.print());

  try {
    if (window.location.protocol === "file:") {
      throw new Error(
        "Job briefs need the local server. Open CorridorIQ HQ or http://127.0.0.1:8000/reports.html?report=qualifying"
      );
    }
    const params = new URLSearchParams(window.location.search);
    const j = params.get("j") || "";
    const p = params.get("p") || "";
    if (!j || !p) {
      throw new Error("Missing job link. Open a permit number from the Priority Outreach list.");
    }

    const res = await fetch("data/exports/job_briefs.json", { cache: "no-store" });
    if (!res.ok) {
      throw new Error(
        `Could not load job_briefs.json (HTTP ${res.status}). Run: python pipeline/run.py reports`
      );
    }
    const payload = await res.json();
    const key = `${j}|${p}`;
    const job = payload.jobs?.[key];
    if (!job) {
      throw new Error(
        `No polished brief found for ${p} (${j}). Regenerate with: python pipeline/run.py reports`
      );
    }
    loading.style.display = "none";
    renderJob(job, payload.generated_at);
  } catch (err) {
    loading.style.display = "none";
    error.style.display = "block";
    error.innerHTML = `${escapeHtml(err.message || String(err))}<br><br>
      <a class="inline-link" href="reports.html?report=qualifying&amp;view=polished">Back to qualifying report</a>`;
  }
}

init();
